### ISSUE TITLE
能不能直接连音符和歌词都提取了

### ISSUE THREAD

**Issue by woaiyan2222** [oxygen-dioxide/dspitch#1]
试了音高线提没问题，要是音符和歌词都一起提取了就好了

**Comment by woaiyan2222** [comment]
这标题咋改我也不知道怎么写的额，好像写错了

**Comment by oxygen-dioxide** [comment]
从技术上做不到，因为OpenUtau中，音素必须通过音素器由音符生成，而不能任意设置音素序列。而且utau插件也无法访问音素。

**Comment by woaiyan2222** [comment]
我用ACE的导出mid可以导入歌词音符在openutau，所以就想那可以把*.ds先变成mid然后在导入openutau吗?

**Comment by oxygen-dioxide** [comment]
没有支持ds文件转换为其他格式的打算。ds并非为音乐创作工程的存储而设计，不包含曲速和节拍等音乐信息。ds仅适合前端编辑器向后端歌声合成引擎的单向数据传输。
这个插件仅仅是在OpenUtau支持diffsinger音高模型前的一个临时解决方案，用于将python推理得到的音高曲线导入OpenUtau。现在OpenUtau已支持diffsinger音高模型，这个插件不再开发（而且UTAU插件开发实在是麻烦）
另外想问一下，你的ds文件是怎么获得的？

**Comment by woaiyan2222** [comment]
diffsinger制作音高数据的方式，但得到的ds并不好，SlurCutter不太好用

**Comment by woaiyan2222** [comment]
也可能是我不太会用。。。。
